apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    
spec:
  ingressClassName: nginx
  tls:  # Configure TLS settings
  - hosts:
      - vprofile.instantsummaries.online  # The domain for which the certificate is issued
     
  rules:
  - host: vprofile.instantsummaries.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              number: 8080
